import HomePage from "@/src/components/home/HomePage";
import Head from "next/head";


export default function Home() {

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sign in</title>

      </Head>

      <HomePage />

    </>
  );
}
