import Dashboard from '@/src/components/dashboard/Dashboard'
import Head from 'next/head'
import React from 'react'

function DashboardStatus({ servers, history }) {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Dashboard servers={servers} history={history} />
        </>
    )
}

export default DashboardStatus

export async function getStaticProps() {
    const { servers, historical_data } = await import('../../data/server_status.json');

    return {
        props: {
            servers: servers,
            history: historical_data
        }
    }
}